language: node_js
node_js:
  - "7.2.1"
script:
  - npm install
  - ng build --prod
  - cd functions & npm install  
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN