language: node_js
node_js:
  - "7.2.1"
script:
  - npm install
  - npm --prefix functions install functions
  - ng build --prod 
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN